
#
## Install install and configure the application.
#

# This command downloads the contents of the specified S3 bucket to the '/var/www/html' directory on the EC2 instance
sudo aws s3 sync s3://dee-app-bucket /var/www/html

# This command changes the current working directory to '/var/www/html', which is the standard directory for hosting web pages on a Unix-based server
cd /var/www/html

# This command is used to extract the contents of the application code zip file that was previously downloaded from the S3 bucket
sudo unzip nest-app.zip

# This command recursively copies all files, including hidden ones, from the 'nest-app' directory to the '/var/www/html/'.
sudo cp -R nest-app/. /var/www/html/

# This command permanently deletes the 'nest-app' directory and the 'nest-app.zip' file.
sudo rm -rf nest-app nest-app.zip

# This command set permissions 777 for the '/var/www/html' directory and the 'storage/' directory
sudo chmod -R 777 /var/www/html
sudo chmod -R 777 storage/

# This command use sed to search the .env file for a line that starts with APP_URL= and replace everything after the = character with the app's domain name
sudo sed -i "/^APP_URL=/ s/=.*$/=https:\/\/www.peprah4jd.click\//" .env

# This command use sed to search the .env file for a line that starts with DB_HOST= and replace everything after the = character with the rds endpoint
sudo sed -i "/^DB_HOST=/ s/=.*$/=testdb.c3qgmy74n7ea.eu-west-2.rds.amazonaws.com/" .env

# This command use sed to search the .env file for a line that starts with DB_DATABASE= and replace everything after the = character with the rds database name
sudo sed -i "/^DB_DATABASE=/ s/=.*$/=adwoadb/" .env

# This command use sed to search the .env file for a line that starts with DB_USERNAME= and replace everything after the = character with the rds database username
sudo sed -i "/^DB_USERNAME=/ s/=.*$/=dee/" .env

# This command use sed to search the .env file for a line that starts with DB_PASSWORD= and replace everything after the = character with the rds database password
sudo sed -i "/^DB_PASSWORD=/ s/=.*$/=dee12345/" .env

# This command will restart the Apache server
sudo service httpd restart



