
# APP Configuration
# nest app sript 

# install and configure the application 

# change current directory to the html 
cd /var/wwww/html

# 4a. in the html directory, command to download the provided code from s3 bucket to the '/var/www/html'
sudo aws s3 cp s3://dee-app-bucket/nest-app.zip .


# command to unzip  and extract content for the application 
sudo unzip nest-app.zip

# This command to copy all files, including hidden ones, from the 'nest-app' directory to the '/var/www/html/'.
sudo cp -R nest-app/. /var/www/html/

# This command to delet the 'nest-app' directory and the 'nest-app.zip' file.
sudo rm -rf nest-app nest-app.zip

# Step 2 of deploying Dynamic web

# still in the html directory , run the command to to give permission to env file APP_URL=enter your domain name
sudo chmod -R 777 /var/www/html
sudo chmod -R 777 storage/

# command to search for the .env file for a line that starts with APP_URL= and replace everything after the = character with the domain name and database credential 
sudo sed -i "/^APP_URL=/s/.*/APP_URL=www.peprah4jd.click/" .env

# command to use sed to search for the .env file for a line that starts with DB_HOST= and replace everything after the = character with the domain name and database credential
sudo sed -i 's|^DB_HOST=.*|DB_HOST="testdb.c3qgmy74n7ea.eu-west-2.rds.amazonaws.com"|' /var/www/html/.env

# command to use sed to search .env file for a line that starts wirh DB_DATABASE replace everything after the = character with the domain name and database credential
sudo sed -i 's|^DB_DATABASE=.*|DB_DATABASE="adwoadb"|' /var/www/html/.env

# command to use sed to search .env file for a line that starts wiith DB_USERNAME replace everything after the = character with the domain name and database credential
sudo sed -i 's|^DB_USERNAME=.*|DB_USERNAME="dee"|' /var/www/html/.env

# command to use sed to search .env file for a line that starts wiith DB_PASSWORD replace everything after the = character with the domain name and database credential
sed -i 's|^DB_PASSWORD=.*|DB_PASSWORD="dee12345"|' /var/www/html/.env

#  command to restart the Apache server
sudo service httpd restart

# Final step 
# Replace the 'AppServiceProvider.php' file 
# step 3 of deploying dynamic web



<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        if (env('APP_ENV') === 'production') {\Illuminate\Support\Facades\URL::forceScheme('https');}
        //
    }
}