# APP Configuration
# nest app sript 
# Step 2 of deploying Dynamic web
# command to to give permission to env file APP_URL=enter your domain name
chmod -R 777 /var/www/html
chmod -R 777 storage/

# command to search for the .env file for a line that starts with APP_URL= and replace everything after the = character with the domain name and database credential 
sudo sed -i "/^APP_URL=/s/.*/APP_URL=www.peprah4jd.click/" .env

# command to use sed to search for the .env file for a line that starts with DB_HOST= and replace everything after the = character with the domain name and database credential
sed -i 's|^DB_HOST=.*|DB_HOST="prodb.c3qgmy74n7ea.eu-west-2.rds.amazonaws.com"|' /var/www/html/.env

# command to use sed to search .env file for a line that starts wirh DB_DATABASE replace everything after the = character with the domain name and database credential
sed -i 's|^DB_DATABASE=.*|DB_DATABASE="Deepro"|' /var/www/html/.env

# command to use sed to search .env file for a line that starts wiith DB_USERNAME replace everything after the = character with the domain name and database credential
sed -i 's|^DB_USERNAME=.*|DB_USERNAME="Deepro"|' /var/www/html/.env

# command to use sed to search .env file for a line that starts wiith DB_PASSWORD replace everything after the = character with the domain name and database credential
sed -i 's|^DB_PASSWORD=.*|DB_PASSWORD="Deepro12345"|' /var/www/html/.env


# Final step 
# Replace the 'AppServiceProvider.php' file 
# step 3 of deploying dynamic web

<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        if (env('APP_ENV') === 'production') {\Illuminate\Support\Facades\URL::forceScheme('https');}
        //
    }
}